BEGIN TRANSACTION;


INSERT INTO certification (certification_id, certification_name) VALUES (5, 'Organic');
INSERT INTO certification (certification_id, certification_name) VALUES (6, 'Non-GMO');
INSERT INTO certification (certification_id, certification_name) VALUES (7, 'Gluten-Free');


INSERT into certification_product (product_id, certification_id) VALUES (2, 2);
INSERT into certification_product (product_id, certification_id) VALUES (2,4);
INSERT into certification_product (product_id, certification_id) VALUES (3,5);
INSERT into certification_product (product_id, certification_id) VALUES (3,6);
INSERT into certification_product (product_id, certification_id) VALUES (5,2);
INSERT into certification_product (product_id, certification_id) VALUES (6,3);
INSERT into certification_product (product_id, certification_id) VALUES (7,5);
INSERT into certification_product (product_id, certification_id) VALUES (7,6);
INSERT into certification_product (product_id, certification_id) VALUES (8,2);
INSERT into certification_product (product_id, certification_id) VALUES (9,2);
INSERT into certification_product (product_id, certification_id) VALUES (9,4);
INSERT into certification_product (product_id, certification_id) VALUES (10,5);
INSERT into certification_product (product_id, certification_id) VALUES (11,3);
INSERT into certification_product (product_id, certification_id) VALUES (11,5);
UPDATE certification_product SET certification_id = 4 WHERE product_id = 12;
UPDATE certification_product SET certification_id = 4 WHERE product_id = 13;
UPDATE certification_product SET certification_id = 4 WHERE product_id = 14;
UPDATE certification_product SET certification_id = 4 WHERE product_id = 15;
UPDATE certification_product SET certification_id = 6 WHERE product_id = 16;
UPDATE certification_product SET certification_id = 5 WHERE product_id = 17;
INSERT into certification_product (product_id, certification_id) VALUES (18,3);
INSERT into certification_product (product_id, certification_id) VALUES (19, 7);
INSERT into certification_product (product_id, certification_id) VALUES (20,3);
INSERT into certification_product (product_id, certification_id) VALUES (20,5);
INSERT into certification_product (product_id, certification_id) VALUES (21,4);
INSERT into certification_product (product_id, certification_id) VALUES (22,2);
INSERT into certification_product (product_id, certification_id) VALUES (23,3);
INSERT into certification_product (product_id, certification_id) VALUES (23,5);
UPDATE certification_product SET certification_id = 4 WHERE product_id = 26;
UPDATE certification_product SET certification_id = 4 WHERE product_id = 27;
INSERT into certification_product (product_id, certification_id) VALUES (28,3);
INSERT into certification_product (product_id, certification_id) VALUES (29,2);
INSERT into certification_product (product_id, certification_id) VALUES (29,5);
UPDATE certification_product SET certification_id = 4 WHERE product_id = 30;
INSERT into certification_product (product_id, certification_id) VALUES (31,5);
INSERT into certification_product (product_id, certification_id) VALUES (32,2);
INSERT into certification_product (product_id, certification_id) VALUES (33,5);
INSERT into certification_product (product_id, certification_id) VALUES (34,3);
INSERT into certification_product (product_id, certification_id) VALUES (35,2);
INSERT into certification_product (product_id, certification_id) VALUES (36,2);
INSERT into certification_product (product_id, certification_id) VALUES (37,2);
INSERT into certification_product (product_id, certification_id) VALUES (39,5);
INSERT into certification_product (product_id, certification_id) VALUES (39,7);
INSERT into certification_product (product_id, certification_id) VALUES (41,3);
INSERT into certification_product (product_id, certification_id) VALUES (41,5);
INSERT into certification_product (product_id, certification_id) VALUES (42,4);
INSERT into certification_product (product_id, certification_id) VALUES (43,3);
INSERT into certification_product (product_id, certification_id) VALUES (43,5);
INSERT into certification_product (product_id, certification_id) VALUES (44,3);
INSERT into certification_product (product_id, certification_id) VALUES (44,7);
INSERT into certification_product (product_id, certification_id) VALUES (45,2);
INSERT into certification_product (product_id, certification_id) VALUES (45,5);
INSERT into certification_product (product_id, certification_id) VALUES (45,6);
INSERT into certification_product (product_id, certification_id) VALUES (47,1);
INSERT into certification_product (product_id, certification_id) VALUES (49,3);
INSERT into certification_product (product_id, certification_id) VALUES (49,1);
INSERT into certification_product (product_id, certification_id) VALUES (50,2);
INSERT into certification_product (product_id, certification_id) VALUES (50,4);
INSERT into certification_product (product_id, certification_id) VALUES (51,4);
INSERT into certification_product (product_id, certification_id) VALUES (52,2);
INSERT into certification_product (product_id, certification_id) VALUES (52,3);
INSERT into certification_product (product_id, certification_id) VALUES (52,4);
INSERT into certification_product (product_id, certification_id) VALUES (53,4);
INSERT into certification_product (product_id, certification_id) VALUES (54,4);
UPDATE product SET title = 'Hamburger Buns' WHERE product_id = 54;
INSERT into certification_product (product_id, certification_id) VALUES (55, 4);
INSERT into certification_product (product_id, certification_id) VALUES (55,5);
INSERT into certification_product (product_id, certification_id) VALUES (55,6);
INSERT into certification_product (product_id, certification_id) VALUES (56,4);
INSERT into certification_product (product_id, certification_id) VALUES (57,4);
INSERT into certification_product (product_id, certification_id) VALUES (58,4);
INSERT into certification_product (product_id, certification_id) VALUES (59,4);
INSERT into certification_product (product_id, certification_id) VALUES (60,4);
INSERT into certification_product (product_id, certification_id) VALUES (61,4);
INSERT into certification_product (product_id, certification_id) VALUES (62,4);
INSERT into certification_product (product_id, certification_id) VALUES (62,1);
INSERT into certification_product (product_id, certification_id) VALUES (63,4);
INSERT into certification_product (product_id, certification_id) VALUES (64,4);
INSERT into certification_product (product_id, certification_id) VALUES (65,4);
INSERT into certification_product (product_id, certification_id) VALUES (66,1);
INSERT into certification_product (product_id, certification_id) VALUES (66,7);
INSERT into certification_product (product_id, certification_id) VALUES (67,5);
INSERT into certification_product (product_id, certification_id) VALUES (67,4);
INSERT into certification_product (product_id, certification_id) VALUES (68,4);
INSERT into certification_product (product_id, certification_id) VALUES (69,1);
INSERT into certification_product (product_id, certification_id) VALUES (69,6);
INSERT into certification_product (product_id, certification_id) VALUES (69,7);
INSERT into certification_product (product_id, certification_id) VALUES (70,4);

COMMIT TRANSACTION;